// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrTN2VzFvotn0_Qkng-QgquL-NDT_VJSE',
    appId: '1:723643128156:web:7883386cb41a7a44c44999',
    messagingSenderId: '723643128156',
    projectId: 'zene-luxury',
    authDomain: 'zene-luxury.firebaseapp.com',
    storageBucket: 'zene-luxury.firebasestorage.app',
    measurementId: 'G-X51YR1R9Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwgqecUF_7i1DOPGj6HEx89jYziLSrWBk',
    appId: '1:723643128156:android:3b6aabf914fad62ac44999',
    messagingSenderId: '723643128156',
    projectId: 'zene-luxury',
    storageBucket: 'zene-luxury.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOGG9RY0UJIaHM37i7Lnw1Fbi_53x7Dlg',
    appId: '1:723643128156:ios:168b78a06b5cf545c44999',
    messagingSenderId: '723643128156',
    projectId: 'zene-luxury',
    storageBucket: 'zene-luxury.firebasestorage.app',
    iosBundleId: 'com.example.cottonApp',
  );
}
